# LinkedIn Skills Suite — First-time setup
# Creates client config and log files that are gitignored.
# Safe to re-run: skips files that already exist.

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "LinkedIn Skills Suite - Setup" -ForegroundColor Cyan
Write-Host "=============================" -ForegroundColor Cyan
Write-Host ""

# --- Directories ---
$dirs = @(
    "linkedin-core/references"
    "linkedin-core/shared/logs"
    "linkedin-core/shared/references"
    "linkedin-core/shared/scripts"
    "linkedin-connect-timer/logs"
    "linkedin-daily-planner/logs"
    "linkedin-icp-warmer/logs"
    "linkedin-icp-finder/references"
    "web-icp-scanner"
)

foreach ($d in $dirs) {
    if (-not (Test-Path $d)) {
        New-Item -ItemType Directory -Path $d -Force | Out-Null
        Write-Host "  Created directory: $d" -ForegroundColor Green
    }
}

# --- Helper: write placeholder if file doesn't exist ---
function New-Placeholder {
    param(
        [string]$Path,
        [string]$Content
    )
    if (-not (Test-Path $Path)) {
        Set-Content -Path $Path -Value $Content -Encoding UTF8
        Write-Host "  Created: $Path" -ForegroundColor Green
    } else {
        Write-Host "  Exists:  $Path" -ForegroundColor DarkGray
    }
}

# --- Client config (generated by linkedin-onboarding) ---
$configPlaceholder = "# Not configured`n`n> Run ``linkedin-onboarding`` to generate this file."

New-Placeholder "linkedin-core/references/icp-profile.md"            $configPlaceholder
New-Placeholder "linkedin-core/references/contact-classification.md"  $configPlaceholder
New-Placeholder "linkedin-core/references/connect-request.md"         $configPlaceholder
New-Placeholder "linkedin-core/references/saved-asset.md"             $configPlaceholder
New-Placeholder "linkedin-core/references/linkedin-strategy.md"       $configPlaceholder
New-Placeholder "linkedin-core/references/company-pages-config.md"    $configPlaceholder
New-Placeholder "linkedin-core/references/linkedin-framework.md"      $configPlaceholder
New-Placeholder "linkedin-core/references/target-list.md"             $configPlaceholder
New-Placeholder "linkedin-core/references/client-profile.json" @'
{
  "CLIENT_BRAND_PRIMARY": "Primary Brand",
  "CLIENT_BRAND_SECONDARY": "Secondary Brand",
  "CLIENT_COMMUNITY_NAME": "Community Name",
  "CLIENT_FOUNDER_NAME": "Founder Name",
  "CLIENT_LINKEDIN_HANDLE": "linkedin-handle",
  "CLIENT_TIMEZONE": "UTC",
  "CLIENT_TARGET_GEO": "Target Region",
  "CLIENT_TARGET_GEO_LIST": "Country A, Country B",
  "CLIENT_WORKSPACE_ROOT": "C:\\Users\\<user>\\linkedin-skills-suite",
  "CLIENT_LOCAL_USER": "<user>"
}
'@

# --- Account config ---
New-Placeholder "linkedin-core/shared/linkedin-account-config.md"                       $configPlaceholder

# --- Activity logs ---
$logPlaceholder = "# Activity Log`n`nNo activity recorded yet."

New-Placeholder "linkedin-core/shared/logs/linkedin-activity.md"            $logPlaceholder
New-Placeholder "linkedin-core/shared/logs/icp-prospects.md"                $logPlaceholder
New-Placeholder "linkedin-core/shared/logs/linkedin-blacklist.md"           $logPlaceholder
New-Placeholder "linkedin-core/shared/logs/inbound-screening-history.md"    $logPlaceholder
New-Placeholder "linkedin-core/shared/logs/company-pages-activity.md"       $logPlaceholder
New-Placeholder "linkedin-core/shared/logs/x-activity.md"                   $logPlaceholder
New-Placeholder "linkedin-core/shared/logs/whatsapp-activity.md"            $logPlaceholder
New-Placeholder "linkedin-core/shared/logs/instagram-activity.md"           $logPlaceholder
New-Placeholder "linkedin-core/shared/logs/thought-leaders-agentic-ai.md"   $logPlaceholder
New-Placeholder "linkedin-core/shared/logs/algorithm-changes.md"            $logPlaceholder
New-Placeholder "linkedin-core/shared/logs/video-activity.md"               $logPlaceholder
New-Placeholder "linkedin-connect-timer/logs/activity-log.md" $logPlaceholder
New-Placeholder "linkedin-icp-warmer/logs/warmup-runs.md"     $logPlaceholder
New-Placeholder "linkedin-icp-finder/references/icp-profile.md" $configPlaceholder

# --- Web ICP scanner ---
New-Placeholder "web-icp-scanner/web-discovered-prospects.md"             $logPlaceholder
New-Placeholder "web-icp-scanner/icp-learning-log.md"                     $logPlaceholder
New-Placeholder "web-icp-scanner/prospect-linkedin-search-results.json"   "{}"

Write-Host ""
Write-Host "Setup complete!" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Open Codex in this directory"
Write-Host "  2. Run: linkedin-onboarding"
Write-Host "  3. Run: start linkedin"
Write-Host ""
