#!/usr/bin/env bash
# LinkedIn Skills Suite — First-time setup
# Creates client config and log files that are gitignored.
# Safe to re-run: skips files that already exist.

set -e

echo ""
echo "LinkedIn Skills Suite - Setup"
echo "============================="
echo ""

# --- Directories ---
dirs=(
    "linkedin-core/references"
    "linkedin-core/shared/logs"
    "linkedin-core/shared/references"
    "linkedin-core/shared/scripts"
    "linkedin-connect-timer/logs"
    "linkedin-daily-planner/logs"
    "linkedin-icp-warmer/logs"
    "linkedin-icp-finder/references"
    "web-icp-scanner"
)

for d in "${dirs[@]}"; do
    if [ ! -d "$d" ]; then
        mkdir -p "$d"
        echo "  Created directory: $d"
    fi
done

# --- Helper: write placeholder if file doesn't exist ---
create_placeholder() {
    local path="$1"
    local content="$2"
    if [ ! -f "$path" ]; then
        echo "$content" > "$path"
        echo "  Created: $path"
    else
        echo "  Exists:  $path"
    fi
}

# --- Client config (generated by linkedin-onboarding) ---
CONFIG_PLACEHOLDER="# Not configured

> Run \`linkedin-onboarding\` to generate this file."

LOG_PLACEHOLDER="# Activity Log

No activity recorded yet."

# Config files
create_placeholder "linkedin-core/references/icp-profile.md"            "$CONFIG_PLACEHOLDER"
create_placeholder "linkedin-core/references/contact-classification.md"  "$CONFIG_PLACEHOLDER"
create_placeholder "linkedin-core/references/connect-request.md"         "$CONFIG_PLACEHOLDER"
create_placeholder "linkedin-core/references/saved-asset.md"             "$CONFIG_PLACEHOLDER"
create_placeholder "linkedin-core/references/linkedin-strategy.md"       "$CONFIG_PLACEHOLDER"
create_placeholder "linkedin-core/references/company-pages-config.md"    "$CONFIG_PLACEHOLDER"
create_placeholder "linkedin-core/references/linkedin-framework.md"      "$CONFIG_PLACEHOLDER"
create_placeholder "linkedin-core/references/target-list.md"             "$CONFIG_PLACEHOLDER"
create_placeholder "linkedin-core/references/client-profile.json" '{
  "CLIENT_BRAND_PRIMARY": "Primary Brand",
  "CLIENT_BRAND_PRIMARY_SLUG": "primary-brand-linkedin-slug",
  "CLIENT_BRAND_SECONDARY": "Secondary Brand",
  "CLIENT_BRAND_SECONDARY_SLUG": "secondary-brand-linkedin-slug",
  "CLIENT_COMMUNITY_NAME": "Community Name",
  "CLIENT_COMMUNITY_SLUG": "community-linkedin-slug",
  "CLIENT_FOUNDER_NAME": "Founder Name",
  "CLIENT_GSHEETS_CREDENTIALS_FILE": "gsheets-service-account.json",
  "CLIENT_GSHEETS_PROJECT_ID": "your-google-project-id",
  "CLIENT_GSHEETS_SERVICE_ACCOUNT_EMAIL": "mcp-gsheets@your-project.iam.gserviceaccount.com",
  "CLIENT_LINKEDIN_HANDLE": "linkedin-handle",
  "CLIENT_TIMEZONE": "UTC",
  "CLIENT_TARGET_GEO": "Target Region",
  "CLIENT_TARGET_GEO_LIST": "Country A, Country B",
  "CLIENT_WORKSPACE_ROOT": "C:\\Users\\<user>\\linkedin-skills-suite",
  "CLIENT_LOCAL_USER": "<user>"
}'

# Account config
create_placeholder "linkedin-core/shared/linkedin-account-config.md"                        "$CONFIG_PLACEHOLDER"

# Activity logs
create_placeholder "linkedin-core/shared/logs/linkedin-activity.md"            "$LOG_PLACEHOLDER"
create_placeholder "linkedin-core/shared/logs/icp-prospects.md"                "$LOG_PLACEHOLDER"
create_placeholder "linkedin-core/shared/logs/linkedin-blacklist.md"           "$LOG_PLACEHOLDER"
create_placeholder "linkedin-core/shared/logs/inbound-screening-history.md"    "$LOG_PLACEHOLDER"
create_placeholder "linkedin-core/shared/logs/company-pages-activity.md"       "$LOG_PLACEHOLDER"
create_placeholder "linkedin-core/shared/logs/x-activity.md"                   "$LOG_PLACEHOLDER"
create_placeholder "linkedin-core/shared/logs/whatsapp-activity.md"            "$LOG_PLACEHOLDER"
create_placeholder "linkedin-core/shared/logs/instagram-activity.md"           "$LOG_PLACEHOLDER"
create_placeholder "linkedin-core/shared/logs/thought-leaders-agentic-ai.md"   "$LOG_PLACEHOLDER"
create_placeholder "linkedin-core/shared/logs/algorithm-changes.md"            "$LOG_PLACEHOLDER"
create_placeholder "linkedin-core/shared/logs/video-activity.md"               "$LOG_PLACEHOLDER"
create_placeholder "linkedin-core/shared/logs/browser-usage-metrics.md" "# Browser Usage Metrics

| Date | Block/Run | Skill | Cache_Hits | Cache_Misses | Browser_Page_Opens | Browser_Snapshots | Browser_Navigations | Browser_Minutes | Deferred_Tasks | Notes |
|---|---|---|---:|---:|---:|---:|---:|---:|---:|---|"
create_placeholder "linkedin-connect-timer/logs/activity-log.md" "$LOG_PLACEHOLDER"
create_placeholder "linkedin-icp-warmer/logs/warmup-runs.md"     "$LOG_PLACEHOLDER"
create_placeholder "linkedin-icp-finder/references/icp-profile.md" "$CONFIG_PLACEHOLDER"

# Web ICP scanner
create_placeholder "web-icp-scanner/web-discovered-prospects.md"           "$LOG_PLACEHOLDER"
create_placeholder "web-icp-scanner/icp-learning-log.md"                   "$LOG_PLACEHOLDER"
create_placeholder "web-icp-scanner/prospect-linkedin-search-results.json" "{}"

echo ""
echo "Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Open Codex in this directory"
echo "  2. Run: linkedin-onboarding"
echo "  3. Run: start linkedin"
echo ""
