#!/usr/bin/env bash
# LinkedIn Skills Suite — First-time setup
# Creates client config and log files that are gitignored.
# Safe to re-run: skips files that already exist.

set -e

echo ""
echo "LinkedIn Skills Suite - Setup"
echo "============================="
echo ""

# --- Directories ---
dirs=(
    "references"
    "shared/logs"
    "linkedin-connect-timer/logs"
    "linkedin-daily-planner/shared/logs"
    "linkedin-daily-planner/logs"
    "linkedin-icp-warmer/logs"
    "linkedin-icp-finder/references"
    "web-icp-scanner"
)

for d in "${dirs[@]}"; do
    if [ ! -d "$d" ]; then
        mkdir -p "$d"
        echo "  Created directory: $d"
    fi
done

# --- Helper: write placeholder if file doesn't exist ---
create_placeholder() {
    local path="$1"
    local content="$2"
    if [ ! -f "$path" ]; then
        echo "$content" > "$path"
        echo "  Created: $path"
    else
        echo "  Exists:  $path"
    fi
}

# --- Client config (generated by linkedin-onboarding) ---
CONFIG_PLACEHOLDER="# Not configured

> Run \`linkedin-onboarding\` to generate this file."

LOG_PLACEHOLDER="# Activity Log

No activity recorded yet."

# Config files
create_placeholder "references/icp-profile.md"            "$CONFIG_PLACEHOLDER"
create_placeholder "references/contact-classification.md"  "$CONFIG_PLACEHOLDER"
create_placeholder "references/connect-request.md"         "$CONFIG_PLACEHOLDER"
create_placeholder "references/saved-asset.md"             "$CONFIG_PLACEHOLDER"
create_placeholder "references/linkedin-strategy.md"       "$CONFIG_PLACEHOLDER"
create_placeholder "references/company-pages-config.md"    "$CONFIG_PLACEHOLDER"

# Account config
create_placeholder "shared/linkedin-account-config.md"                        "$CONFIG_PLACEHOLDER"
create_placeholder "linkedin-daily-planner/shared/linkedin-account-config.md" "$CONFIG_PLACEHOLDER"

# Activity logs
create_placeholder "shared/logs/linkedin-activity.md"            "$LOG_PLACEHOLDER"
create_placeholder "shared/logs/icp-prospects.md"                "$LOG_PLACEHOLDER"
create_placeholder "shared/logs/linkedin-blacklist.md"           "$LOG_PLACEHOLDER"
create_placeholder "shared/logs/inbound-screening-history.md"    "$LOG_PLACEHOLDER"
create_placeholder "shared/logs/company-pages-activity.md"       "$LOG_PLACEHOLDER"
create_placeholder "shared/logs/x-activity.md"                   "$LOG_PLACEHOLDER"
create_placeholder "shared/logs/whatsapp-activity.md"            "$LOG_PLACEHOLDER"
create_placeholder "shared/logs/instagram-activity.md"           "$LOG_PLACEHOLDER"
create_placeholder "shared/logs/thought-leaders-agentic-ai.md"   "$LOG_PLACEHOLDER"
create_placeholder "shared/logs/algorithm-changes.md"            "$LOG_PLACEHOLDER"
create_placeholder "shared/logs/video-activity.md"               "$LOG_PLACEHOLDER"
create_placeholder "linkedin-connect-timer/logs/activity-log.md" "$LOG_PLACEHOLDER"
create_placeholder "linkedin-daily-planner/shared/logs/linkedin-activity.md" "$LOG_PLACEHOLDER"
create_placeholder "linkedin-daily-planner/shared/logs/icp-prospects.md"     "$LOG_PLACEHOLDER"
create_placeholder "linkedin-icp-warmer/logs/warmup-runs.md"     "$LOG_PLACEHOLDER"
create_placeholder "linkedin-icp-finder/references/icp-profile.md" "$CONFIG_PLACEHOLDER"

# Web ICP scanner
create_placeholder "web-icp-scanner/web-discovered-prospects.md"           "$LOG_PLACEHOLDER"
create_placeholder "web-icp-scanner/icp-learning-log.md"                   "$LOG_PLACEHOLDER"
create_placeholder "web-icp-scanner/prospect-linkedin-search-results.json" "{}"

echo ""
echo "Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Open Claude Code in this directory"
echo "  2. Run: linkedin-onboarding"
echo "  3. Run: start linkedin"
echo ""
